config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions, except: [:edit] do
    resources :answers, only: [:create, :update, :destroy], shallow: true do
      member do
        post :mark_as_best
      end
    end

    resources :notifications, only: [:create, :destroy], shallow: true
  end

  resources :rewards, only: [:index]

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]

  concern :voteable do |options|
    member do
      resources :votes, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'question' }, as: :question_votes
  end

  resources :answers, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'answer' }, as: :answer_votes
  end

  resources :votes, only: [:destroy]

  concern :commentable do |options|
    member do
      resources :comments, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'question' }, as: :question_comments
  end

  resources :answers, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'answer' }, as: :answer_comments
  end

  get '/a/:enter_email_token/ee', to: 'authorizations#enter_email', as: :auth_enter_email
  post '/a/:enter_email_token/ue', to: 'authorizations#update_email', as: :auth_update_email
  get '/a/:confirm_email_token/ce', to: 'authorizations#confirm_email', as: :auth_confirm_email

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  resources :search, only: [] do
    collection do
      get :global
      get :questions
      get :answers
      get :comments
      get :users
    end
  end

  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  rescue_from Services::Search::Base::EmptySearchError, with: :empty_search_error

  def global
    respond_to do |format|
      format.html
      format.json { render json: Services::Search::Global.new.call(search_params).to_a, each_serializer: Search::GlobalSerializer, adapter: :attributes }
    end
  end

  def questions
    respond_to do |format|
      format.html
      format.json { render_json(Services::Search::Questions.new.call(search_params)) }
    end
  end

  def answers
    respond_to do |format|
      format.html
      format.json { render_json(Services::Search::Answers.new.call(search_params)) }
    end
  end

  def comments
    respond_to do |format|
      format.html
      format.json { render_json(Services::Search::Comments.new.call(search_params)) }
    end
  end

  def users
    respond_to do |format|
      format.html
      format.json { render_json(Services::Search::Users.new.call(search_params)) }
    end
  end

  private

  def search_params
    params.require(:search).permit!
  end

  def empty_search_error
    render json: { errors: ['Error: search without params'] }, status: :unprocessable_entity
  end

  def render_json(data)
    render json: { data: data }
  end
end

app/views/search/answers.html.slim
h1 Answers Search

= form_with url: answers_search_index_path(format: :json), method: :get, id: 'answers-search-form' do |f|
  .errors
  p
    = f.label :global
    = f.text_field :global, name: "search[global]"
  p
    = f.label :body
    = f.text_field :body, name: "search[body]"
  p
    = f.label :author
    = f.text_field :author, name: "search[author]"
  p
    = f.submit 'Search'

h2 Result
.result

app/views/search/comments.html.slim
h1 Comments Search

= form_with url: comments_search_index_path(format: :json), method: :get, id: 'comments-search-form' do |f|
  .errors
  p
    = f.label :global
    = f.text_field :global, name: "search[global]"
  p
    = f.label :text
    = f.text_field :text, name: "search[text]"
  p
    = f.label :author
    = f.text_field :author, name: "search[author]"
  p
    = f.submit 'Search'

h2 Result
.result

app/views/search/global.html.slim
h1 Global Search

ul
  li = link_to "Question Search", questions_search_index_path
  li = link_to "Answer Search", answers_search_index_path
  li = link_to "Comment Search", comments_search_index_path
  li = link_to "User Search", users_search_index_path

= form_with url: global_search_index_path(format: :json), method: :get, id: 'global-search-form' do |f|
  .errors
  p
    = f.label :global
    = f.text_field :global, name: "search[global]"
  p
    = f.submit 'Search'

h2 Result
.result

app/views/search/questions.html.slim
h1 Questions Search

= form_with url: questions_search_index_path(format: :json), method: :get, id: 'questions-search-form' do |f|
  .errors
  p
    = f.label :global
    = f.text_field :global, name: "search[global]"
  p
    = f.label :title
    = f.text_field :title, name: "search[title]"
  p
    = f.label :body
    = f.text_field :body, name: "search[body]"
  p
    = f.label :author
    = f.text_field :author, name: "search[author]"
  p
    = f.submit 'Search'

h2 Result
.result

app/views/search/users.html.slim
h1 Users Search

= form_with url: users_search_index_path(format: :json), method: :get, id: 'users-search-form' do |f|
  .errors
  p
    = f.label :global
    = f.text_field :global, name: "search[global]"
  p
    = f.label :email
    = f.text_field :email, name: "search[email]"
  p
    = f.submit 'Search'

h2 Result
.result