config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions, except: [:edit] do
    resources :answers, only: [:create, :update, :destroy], shallow: true do
      member do
        post :mark_as_best
      end
    end

    resources :notifications, only: [:create, :destroy], shallow: true
  end

  resources :rewards, only: [:index]

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]

  concern :voteable do |options|
    member do
      resources :votes, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'question' }, as: :question_votes
  end

  resources :answers, only: [], param: :voteable_id do
    concerns :voteable, defaults: { voteable_type: 'answer' }, as: :answer_votes
  end

  resources :votes, only: [:destroy]

  concern :commentable do |options|
    member do
      resources :comments, { only: [:create] }.merge(options)
    end
  end

  resources :questions, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'question' }, as: :question_comments
  end

  resources :answers, only: [], param: :commentable_id do
    concerns :commentable, defaults: { commentable_type: 'answer' }, as: :answer_comments
  end

  get '/a/:enter_email_token/ee', to: 'authorizations#enter_email', as: :auth_enter_email
  post '/a/:enter_email_token/ue', to: 'authorizations#update_email', as: :auth_update_email
  get '/a/:confirm_email_token/ce', to: 'authorizations#confirm_email', as: :auth_confirm_email

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  resources :search, only: [] do
    collection do
      get :global
      get :questions
      get :answers
      get :comments
      get :users
    end
  end

  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Voteable
  include Commentable

  belongs_to :user
  belongs_to :question

  has_one :question_with_best_answer, class_name: 'Question', foreign_key: :best_answer_id, dependent: :nullify
  has_one :reward, through: :question_with_best_answer

  has_many_attached :files

  before_destroy :unassign_reward, prepend: true

  validates :body, presence: true

  scope :bests, -> { where(question: Question.with_best_answer) }

  after_create_commit :send_notification

  def mark_as_best
    question.update(best_answer_id: id)
  end

  def best?
    question.best_answer_id == id
  end

  def assign_reward
    reward&.assign
  end

  def unassign_reward
    reward&.unassign
  end

  private

  def send_notification
    NotificationsJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: [:create]
  before_action :find_answer, only: [:update, :destroy, :mark_as_best]
  before_action :authorize_user!, only: [:update, :destroy, :mark_as_best]

  after_action :publish_answer, only: [:create]

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      flash_notice("The answer has been successfully created")
    else
      flash_alert("The answer has not been created")
    end
  end

  def update
    if @answer.update(answer_params)
      flash_notice("The answer has been successfully updated")
    else
      flash_notice("The answer has not been updated")
    end
  end

  def destroy
    @answer.destroy
    flash_notice("The answer has been successfully deleted")
  end

  def mark_as_best
    Services::Answers::MarkAsBest.new.call(current_user, @answer)
  rescue Services::Answers::MarkAsBest::UserNotAuthorError
    flash_alert("You can't mark the answer, because you aren't author the question")
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def authorize_user!
    authorize @answer
  end

  def publish_answer
    return if @answer.errors.present?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}/answers",
      {
        id: @answer.id,
        author_id: @answer.user_id,
        templates: {
          answer: render_template(
            partial: 'websockets/answers/answer',
            locals: { answer: @answer }
          ),
          vote_links: render_template(
            partial: 'websockets/shared/votes/vote_links',
            locals: { voteable: @answer, vote: @answer.votes.new }
          )
        }
      }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < BaseController
      before_action :find_question, only: [:index, :create]
      before_action :find_answer, only: [:show, :update, :destroy]
      before_action :authorize_user!, only: [:update, :destroy]

      def index
        render json: @question.answers
      end

      def show
        render json: @answer, serializer: FullAnswerSerializer
      end

      def create
        @answer = @question.answers.new(answer_params)
        @answer.user = current_resource_owner

        if @answer.save
          render json: @answer
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def update
        if @answer.update(answer_params)
          render json: @answer, serializer: FullAnswerSerializer
        else
          render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def destroy
        @answer.destroy
        render json: { success: true }
      end

      private

      def answer_params
        params.require(:answer).permit(:body)
      end

      def find_question
        @question = Question.find(params[:question_id])
      end

      def find_answer
        @answer = Answer.with_attached_files.find(params[:id])
      end

      def authorize_user!
        authorize @answer
      end

      def pundit_user
        current_resource_owner
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer id="answer-id-#{answer.id}" class=("best" if local_assigns[:best])
    - cache answer do
      p = answer.body

    = render "/shared/votes/vote_block", vote: (current_user&.vote_by(answer) || answer.votes.new), voteable: answer

    .files
      = render "/files/files_block", files: answer.files

    .links
      = render "/shared/links/links_block", links: answer.links

    - if user_signed_in?
      - if policy(answer).mark_as_best?
        p.mark-as-best = link_to "Mark as best", mark_as_best_answer_path(answer), method: :post, remote: true

      - if policy(answer).edit?
        p = link_to "Edit answer", "#", class: "edit-answer-link", data: { answer_id: answer.id }

        .edit-answer-form
          .answer-errors
          = render "answers/edit_form", answer: answer

      - if policy(answer).destroy?
        p = link_to "Delete answer", answer_path(answer), method: :delete, remote: true

      h4 New comment
      .new-comment-form
        .comment-errors
        = render '/comments/form', commentable: answer

    h4 Comments
    .answer-comments
      = render answer.comments.order(created_at: :asc)

  br

app/views/answers/_edit_form.html.slim
= form_with model: answer, class: "hidden", html: { id: "edit-answer-form-#{answer.id}" } do |f|
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  = render '/shared/links/add_form', f: f
  p
    = f.submit "Save"

app/views/answers/_form.html.slim
= form_with model: [@question, @answer] do |f|
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  = render '/shared/links/nested_form', f: f
  p
    = f.submit "Answer"

app/views/answers/create.js.erb
$(".new-answer-form .answer-errors").html("<%= render "shared/errors", resource: @answer %>");

<% if @answer.persisted? %>
  $(".answers").append("<%= j render @answer %>");
  clearForm($(".new-answer-form"));
  $(".new-answer-form #answer_files").val("");
  $(".new-answer-form #answer_files").prop("disabled", false);
  $(".new-answer-form .direct-upload").remove();
  $(".new-answer-form .nested-fields").remove();
  onAjaxCommentForm($("<%= "#answer-id-#{@answer.id} .new-comment-form form" %>"));
<% end %>

loadGists();

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $(".answers #answer-id-<%= @answer.id %>").remove();
<% end %>

app/views/answers/mark_as_best.js.erb
$(".answers .best .mark-as-best").removeClass("hidden");
$(".answers .best").removeClass("best");
$(".answers #answer-id-<%= @answer.id %>").addClass("best");

app/views/answers/update.js.erb
$("#answer-id-<%= @answer.id %> .edit-answer-form .answer-errors").html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.errors.empty? %>
  $("#answer-id-<%= @answer.id %>").replaceWith("<%= j render @answer, best: @answer.best? %>");
<% end %>

loadGists();